from typing import Protocol

from app.domain.configuration import (
    DetectionSettings,
    Gazetteer,
    GazetteerEntry,
    ModelMapping,
    PatternRecognizer,
    ProtectionRule,
)


class ConfigurationRepository(Protocol):
    async def get_active_model_id(self) -> str | None: ...
    async def set_active_model_id(self, model_id: str) -> None: ...
    async def list_mappings(self, model_id: str) -> list[ModelMapping]: ...
    async def get_mapping(self, mapping_id: int) -> ModelMapping | None: ...
    async def create_mapping(self, mapping: ModelMapping) -> ModelMapping: ...
    async def update_mapping(self, mapping: ModelMapping) -> ModelMapping: ...
    async def delete_mapping(self, mapping_id: int) -> bool: ...
    async def list_patterns(self) -> list[PatternRecognizer]: ...
    async def get_pattern(self, recognizer_id: int) -> PatternRecognizer | None: ...
    async def save_pattern(self, recognizer: PatternRecognizer) -> PatternRecognizer: ...
    async def delete_pattern(self, recognizer_id: int) -> bool: ...
    async def list_gazetteers(self) -> list[Gazetteer]: ...
    async def get_gazetteer(self, gazetteer_id: int) -> Gazetteer | None: ...
    async def save_gazetteer(self, gazetteer: Gazetteer) -> Gazetteer: ...
    async def delete_gazetteer(self, gazetteer_id: int) -> bool: ...
    async def save_gazetteer_entry(
        self,
        gazetteer_id: int,
        entry: GazetteerEntry,
    ) -> GazetteerEntry: ...
    async def delete_gazetteer_entry(self, entry_id: int) -> bool: ...
    async def get_detection_settings(self) -> DetectionSettings: ...
    async def save_detection_settings(self, settings: DetectionSettings) -> DetectionSettings: ...
    async def list_protection_rules(self) -> list[ProtectionRule]: ...
    async def get_protection_rule(self, rule_id: int) -> ProtectionRule | None: ...
    async def save_protection_rule(self, rule: ProtectionRule) -> ProtectionRule: ...
    async def delete_protection_rule(self, rule_id: int) -> bool: ...
    async def commit(self) -> None: ...
